services:
  db:
    image: mysql:8
    container_name: infynia_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  app:
    container_name: infynia_app
    build: .
    restart: always
    # command: /app/docker/entrypoint.sh
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./storage/logs:/app/storage/logs # Mount logs for easier debugging
    depends_on:
      - db

volumes:
  db_data:
  caddy_data:
  caddy_config:
